[package]
name = "BasicCoin"
version = "0.0.1"

[addresses]
BasicCoin = "0xBC"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move", subdir = "language/move-stdlib", rev = "main", addr_subst = { "std" = "0x1" } }
